"""empty message

Revision ID: 3739b9bc1023
Revises: 657daa676a04
Create Date: 2024-10-21 01:38:18.220426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3739b9bc1023'
down_revision: Union[str, None] = '657daa676a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_request', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend_request', 'created_at')
    # ### end Alembic commands ###
