"""empty message

Revision ID: 39dfff115424
Revises: 727432d70cdd
Create Date: 2024-10-15 03:20:30.257761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dfff115424'
down_revision: Union[str, None] = '727432d70cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data_extended',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('unique_id', sa.String(length=58), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'other', name='sexenum'), nullable=True),
    sa.Column('relat_status', sa.Enum('single', 'in_a_relationship', 'married', 'engaged', 'it_s_complicated', 'separated', 'divorced', 'widowed', 'open_to_dating', 'friend_zone', 'looking_for_friends', 'other', name='relationshipstatusenum'), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data_extended')
    # ### end Alembic commands ###
