"""empty message

Revision ID: 6ccb2f3df279
Revises: 9e44a06b905a
Create Date: 2024-10-22 19:59:02.142719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccb2f3df279'
down_revision: Union[str, None] = '9e44a06b905a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chat_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'chat_name')
    # ### end Alembic commands ###
