"""empty message

Revision ID: 727432d70cdd
Revises: 6866f9e3e070
Create Date: 2024-10-15 02:14:25.520887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727432d70cdd'
down_revision: Union[str, None] = '6866f9e3e070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('friend_list', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('user', sa.Column('sent_friend_reqest', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('user', sa.Column('received_friend_requests', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'received_friend_requests')
    op.drop_column('user', 'sent_friend_reqest')
    op.drop_column('user', 'friend_list')
    # ### end Alembic commands ###
