"""empty message

Revision ID: c20382d1f775
Revises: a29fbe4dc74d
Create Date: 2024-10-16 03:19:00.026462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c20382d1f775'
down_revision: Union[str, None] = 'a29fbe4dc74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sent_friend_request', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.drop_column('user', 'sent_friend_reqest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sent_friend_reqest', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False))
    op.drop_column('user', 'sent_friend_request')
    # ### end Alembic commands ###
